name: run-tests

on:
  push:
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        laravel: [ 10.*, 11.* ]
        include:
          - php: 8.1
            laravel: 10.*
            pest: 2.*
            testbench: 8.*
          - php: 8.2
            laravel: 10.*
            pest: 2.*
            testbench: 8.*
          - php: 8.3
            laravel: 10.*
            pest: 2.*
            testbench: 8.*
          - php: 8.2
            laravel: 11.*
            pest: 3.*
            testbench: 9.*
          - php: 8.3
            laravel: 11.*
            pest: 3.*
            testbench: 9.*
        exclude:
          - php: 8.1
            laravel: 11.*

    name: Paragon Tests - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer require "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest }}" --no-interaction --no-update --dev
          composer update --prefer-dist --no-interaction --no-suggest --dev
          composer dump

      - name: Execute tests
        run: composer pest
