name: run-tests

on:
  push:
  pull_request:

jobs:
    pest:
        runs-on: ubuntu-24.04
        timeout-minutes: 5

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.1, 8.2, 8.3 ]
                laravel: [ 10.*, 11.* ]
                include:
                    -   laravel: 11.*
                        testbench: 9.*-dev
                    -   laravel: 10.*
                        testbench: 8.*
                exclude:
                    -   laravel: 11.*
                        php: 8.1

        name: Paragon Tests - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-pw-v2-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                    coverage: none
                    tools: composer:v2

            -   name: Install dependencies
                run: |
                    composer --version
                    composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                    composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
                    composer update --prefer-dist --no-interaction --no-suggest --dev
                    composer dump

            -   name: Execute tests
                run: vendor/bin/pest
